[project]
name = "hello-world-flask"
version = "0.1.0"
description = "dummy project to test flask and have a hello world backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.0"
]
